### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [git-touch/git-touch#239]
```
The current Dart SDK version is 2.10.4.
Because git_touch requires SDK version >=2.12.0 <3.0.0, version solving failed.
```

Which flutter version should be used? Thanks!

**Comment by pd4d10** [comment]
Stable channel should be fine

**Comment by linsui** [comment]
I tried 2.2.1 and it stucked forever.

**Comment by pd4d10** [comment]
This is the version in my local machine:

```sh
> flutter --version
Flutter 2.2.1 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 02c026b03c (7 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Comment by linsui** [comment]
The build recipe is

```yml
  - versionName: 1.12.4
    versionCode: 25
    commit: v1.12.4
    output: build/app/outputs/flutter-apk/app-release.apk
    srclibs:
      - flutter@2.2.1
    build:
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter build apk --no-tree-shake-icons
```

It stuck at

```
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 
This will generate a JSON format file containing all messages that 
need to be translated.
lib/screens/ge_search.dart:28:39: Warning: Operand of null-aware operation '?.' has type 'String' which excludes null.
  String get _keyword => _controller!.text?.trim() ?? '';
                                      ^
lib/screens/gh_repo.dart:273:54: Warning: Operand of null-aware operation '?.' has type 'GRepoCommit_history' which excludes null.
 - 'GRepoCommit_history' is from 'package:git_touch/graphql/github.data.gql.dart' ('lib/graphql/github.data.gql.dart').
                        ((ref.target as GRepoCommit).history?.totalCount ?? 0)
                                                     ^
lib/screens/gl_search.dart:29:39: Warning: Operand of null-aware operation '?.' has type 'String' which excludes null.
  String get _keyword => _controller!.text?.trim() ?? '';
                                      ^
lib/screens/gh_search.dart:28:39: Warning: Operand of null-aware operation '?.' has type 'String' which excludes null.
  String get _keyword => _controller!.text?.trim() ?? '';
                                      ^
```
